// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlEDfblQ7isSBQxJQnUTLKIhbt73WzF3U',
    appId: '1:281144496918:web:0a809f90bfd57241fa3637',
    messagingSenderId: '281144496918',
    projectId: 'lunimuni-6a19d',
    authDomain: 'lunimuni-6a19d.firebaseapp.com',
    storageBucket: 'lunimuni-6a19d.firebasestorage.app',
    measurementId: 'G-5QCL3BBL81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlEDfblQ7isSBQxJQnUTLKIhbt73WzF3U',
    appId: '1:281144496918:android:0a809f90bfd57241fa3637',
    messagingSenderId: '281144496918',
    projectId: 'lunimuni-6a19d',
    storageBucket: 'lunimuni-6a19d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlEDfblQ7isSBQxJQnUTLKIhbt73WzF3U',
    appId: '1:281144496918:ios:0a809f90bfd57241fa3637',
    messagingSenderId: '281144496918',
    projectId: 'lunimuni-6a19d',
    storageBucket: 'lunimuni-6a19d.firebasestorage.app',
    iosBundleId: 'dev.karto.lunimuni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlEDfblQ7isSBQxJQnUTLKIhbt73WzF3U',
    appId: '1:281144496918:ios:0a809f90bfd57241fa3637',
    messagingSenderId: '281144496918',
    projectId: 'lunimuni-6a19d',
    storageBucket: 'lunimuni-6a19d.firebasestorage.app',
    iosBundleId: 'dev.karto.lunimuni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlEDfblQ7isSBQxJQnUTLKIhbt73WzF3U',
    appId: '1:281144496918:web:0a809f90bfd57241fa3637',
    messagingSenderId: '281144496918',
    projectId: 'lunimuni-6a19d',
    authDomain: 'lunimuni-6a19d.firebaseapp.com',
    storageBucket: 'lunimuni-6a19d.firebasestorage.app',
    measurementId: 'G-5QCL3BBL81',
  );
}