# Vision Agent Configuration
# Image analysis and captioning for uploaded drawings

vendor: "google"  # Options: google, openai, anthropic
model: "gemini-2.0-flash-exp"
api_key: ${GOOGLE_API_KEY}

fallback:
  vendor: "openai"
  model: "gpt-4-vision-preview"
  api_key: ${OPENAI_API_KEY}

prompts:
  image_caption:
    default: |
      Describe this image focusing on 3-5 main visual elements:
      - Main subject/character (identify specific objects when recognizable)
      - Colors and textures
      - Setting/background
      - Notable objects
      - Overall mood
      Be factual but include specific names for recognizable items.