# Voice Agent Configuration
# TTS configuration with vendor-based structure for easy switching

# Language-to-vendor mapping - Easy switching point
languages:
  en:
    vendor: "elevenlabs"
    voice: "callum"
  ru:
    # vendor: "elevenlabs" 
    # voice: "nina"
    vendor: "openai"
    voice: "coral"
  lv:
    vendor: "openai"
    voice: "nova"
  es:
    vendor: "elevenlabs"
    voice: "diego_storyteller"
  fr:
    vendor: "elevenlabs"
    voice: "gaelle_storyteller"

# Vendor configurations - API keys and default settings
vendors:
  elevenlabs:
    api_key: ${ELEVENLABS_API_KEY}
    model: "eleven_multilingual_v2"  # Consider upgrading to eleven_turbo_v2_5 or v3 alpha
    default_settings:
      stability: 0.3                # Lower for more emotional range
      similarity_boost: 0.6         # Enhanced clarity
      style: 0.4                    # Higher for more expressiveness
      use_speaker_boost: true       # Better audio quality
      speed: 0.8                    # Default speed
    
    # Language-specific overrides
    language_overrides:
      ru:
        settings:
          similarity_boost: 0.7     # Higher for Russian clarity
          style: 0.5                # Higher emotional expression
          speed: 0.85               # Slower for children's comprehension
      es:
        settings:
          similarity_boost: 0.6     # Enhanced clarity
          style: 0.5                # Higher emotional expression
          speed: 0.85               # Slower pace for comprehension
      fr:
        settings:
          similarity_boost: 0.7     # Higher clarity for French
          style: 0.5                # Higher emotional expression
          speed: 0.85               # Slower pace for comprehension

  openai:
    api_key: ${OPENAI_API_KEY}
    model: "tts-1-hd"               # High quality model for better pronunciation
    default_settings:
      speed: 0.9                    # Slower for better comprehension
      response_format: "mp3"        # More compatible format than FLAC

# Voice alternatives for reference during testing and fallback
available_voices:
  elevenlabs:
    # English voices
    callum: "N2lVS1w4EtoT3dr4eOWO"    # English storyteller (warm male)
    rachel: "21m00Tcm4TlvDq8ikWAM"    # English alternative (gentle female)
    
    # Russian voices
    kate_children_storyteller: "WfExDXCt2GBg6MI5KjQk"  # Russian children storyteller (young female)
    anna_calm: "rxEz5E7hIAPk7D3bXwf6"        # Calm Russian, perfect for kids fairy tales
    igor_bedtime: "rUOpAdbAl56KxO00wR5D"     # Bedtime storyteller, soothing and gentle
    elegant_narrator: "FnNYfPjyvZwLwb043Kl1" # Classic literature voice, warm and expressive
    nina: "N8lIVPsFkvOoqev5Csxo"         # Current voice
    
    # Spanish voices for storytelling
    diego_storyteller: "7vGAwSjuM5RvIjtavbnb"    # Young Spanish male, narration & storytelling
    leonor_bedtime: "ROg7YFURXCUrJKFIrGXT"       # Soft, calm, ideal for bedtime stories
    mateo_chill: "6I5fU8GKAFqBMRcSN7FA"          # Relaxed, warm, authentic tone for stories
    salvador_natural: "egQgipO1HHxedaRzEYJy"     # Professional narration, natural and fluid
    
    # French voices for storytelling  
    gaelle_storyteller: "tKaoyJLW05zqV0tIH9FD"   # Warm, clear, ideal for children stories
    teddy_children: "Y9pL3Tawpspxe35NUtif"       # Soft French Canadian, perfect for children
    thomas_calm: "KLCSI9PVpwo49B6dC7Bo"          # Young male, calm, good for small stories
    luca_expressive: "Ndm6bI6wo3Ycnlx1PPZS"      # Confident, expressive, ideal for storytelling
    
  openai:
    # Standard TTS API voices (available for all languages)
    nova: "Bright, engaging female voice"     # Latvian (best for non-English)
    alloy: "Neutral, versatile voice"         # Fallback option
    fable: "British accent, good for stories" # Alternative for storytelling
    shimmer: "Warm female voice"              # Another female option
    onyx: "Deep male voice"                   # Male alternative
    echo: "Clear male voice"                  # Another male option
    coral: ""                                 # TODO
    sage: ""                                  # TODO
    
    # Note: "sage" only available in Realtime API, not standard TTS

# Emotional storytelling configuration for future v3 alpha upgrade
emotional_storytelling:
  # ElevenLabs v3 alpha audio tags for enhanced emotional expression
  enabled: false  # Enable when upgrading to v3 alpha model
  stability_preset: "creative"  # Options: creative, natural, robust
  audio_tags:
    excitement: "[excited]"
    whisper: "[whispers]" 
    dramatic: "[dramatically]"
    cheerful: "[cheerfully]"
    mysterious: "[mysteriously]"
    scared: "[nervously]"
    happy: "[joyfully]"
    pause: "[pause]"
    # Character voices for different story elements
    monster_voice: "[deep voice]"
    child_voice: "[soft-spoken]"
    narrator_awe: "[awe]"
    dramatic_moment: "[dramatic tone]"