# Voice Agent Configuration
# TTS configuration with vendor-based structure for easy switching

# Language-to-vendor mapping - Easy switching point
languages:
  en:
    # vendor: "elevenlabs"
    # voice: "callum"
    vendor: "openai"
    voice: "coral"
  ru:
    # vendor: "elevenlabs" 
    # voice: "nina"
    vendor: "openai"
    voice: "coral"
  lv:
    vendor: "openai"
    voice: "nova"
  es:
    # vendor: "elevenlabs"
    # voice: "diego_storyteller"
    vendor: "openai"
    voice: "coral"
  fr:
    # vendor: "elevenlabs"
    # voice: "gaelle_storyteller"
    vendor: "openai"
    voice: "coral"

# Vendor configurations - API keys and default settings
vendors:
  elevenlabs:
    api_key: ${ELEVENLABS_API_KEY}
    model: "eleven_multilingual_v2"  # Consider upgrading to eleven_turbo_v2_5 or v3 alpha
    default_settings:
      stability: 0.3                # Lower for more emotional range
      similarity_boost: 0.6         # Enhanced clarity
      style: 0.4                    # Higher for more expressiveness
      use_speaker_boost: true       # Better audio quality
      speed: 0.8                    # Default speed
    
    # Language-specific overrides
    language_overrides:
      ru:
        settings:
          similarity_boost: 0.7     # Higher for Russian clarity
          style: 0.5                # Higher emotional expression
          speed: 0.85               # Slower for children's comprehension
      es:
        settings:
          similarity_boost: 0.6     # Enhanced clarity
          style: 0.5                # Higher emotional expression
          speed: 0.85               # Slower pace for comprehension
      fr:
        settings:
          similarity_boost: 0.7     # Higher clarity for French
          style: 0.5                # Higher emotional expression
          speed: 0.85               # Slower pace for comprehension

  openai:
    api_key: ${OPENAI_API_KEY}
    model: "gpt-4o-mini-tts"        # Latest TTS model with emotional control
    default_settings:
      response_format: "mp3"        # More compatible format than FLAC
      # Voice instructions for children's storytelling
      instructions: "Speak warm and engaging as if reading a children's book. Use a gentle, nurturing tone with natural pauses for comprehension. Express emotions appropriate to the story content - excitement for adventures, wonder for magical moments, and comfort for peaceful scenes. Maintain a storytelling pace that's slightly slower than normal conversation to help children follow along."
    
    # Language-specific voice instructions for enhanced storytelling
    language_overrides:
      ru:
        settings:
          instructions: "Говорите тепло и увлекательно, как будто читаете детскую книгу. Используйте мягкий, заботливый тон с естественными паузами для понимания. Выражайте эмоции, соответствующие содержанию истории - возбуждение для приключений, удивление для волшебных моментов и комфорт для мирных сцен. Поддерживайте темп рассказа немного медленнее обычного разговора."
      lv:
        settings:
          instructions: "Runājiet silti un aizraujoši, it kā lasītu bērnu grāmatu. Lietojiet maigi, rūpīgu toni ar dabiskām pauzēm izpratnei. Izsakiet emocijas, kas atbilst stāsta saturam - uztraukumu piedzīvojumiem, brīnumu maģiskajiem brīžiem un mierinājumu mierīgajām ainām. Uzturiet stāstīšanas tempu nedaudz lēnāku nekā parastā saruna."

# Voice alternatives for reference during testing and fallback
available_voices:
  elevenlabs:
    # English voices
    callum: "N2lVS1w4EtoT3dr4eOWO"    # English storyteller (warm male)
    rachel: "21m00Tcm4TlvDq8ikWAM"    # English alternative (gentle female)
    
    # Russian voices
    kate_children_storyteller: "WfExDXCt2GBg6MI5KjQk"  # Russian children storyteller (young female)
    anna_calm: "rxEz5E7hIAPk7D3bXwf6"        # Calm Russian, perfect for kids fairy tales
    igor_bedtime: "rUOpAdbAl56KxO00wR5D"     # Bedtime storyteller, soothing and gentle
    elegant_narrator: "FnNYfPjyvZwLwb043Kl1" # Classic literature voice, warm and expressive
    nina: "N8lIVPsFkvOoqev5Csxo"         # Current voice
    
    # Spanish voices for storytelling
    diego_storyteller: "7vGAwSjuM5RvIjtavbnb"    # Young Spanish male, narration & storytelling
    leonor_bedtime: "ROg7YFURXCUrJKFIrGXT"       # Soft, calm, ideal for bedtime stories
    mateo_chill: "6I5fU8GKAFqBMRcSN7FA"          # Relaxed, warm, authentic tone for stories
    salvador_natural: "egQgipO1HHxedaRzEYJy"     # Professional narration, natural and fluid
    
    # French voices for storytelling  
    gaelle_storyteller: "tKaoyJLW05zqV0tIH9FD"   # Warm, clear, ideal for children stories
    teddy_children: "Y9pL3Tawpspxe35NUtif"       # Soft French Canadian, perfect for children
    thomas_calm: "KLCSI9PVpwo49B6dC7Bo"          # Young male, calm, good for small stories
    luca_expressive: "Ndm6bI6wo3Ycnlx1PPZS"      # Confident, expressive, ideal for storytelling
    
  openai:
    # GPT-4o-mini-TTS voices (11 premium voices available)
    alloy: "Neutral, versatile voice - great for balanced storytelling"
    ash: "Calm, measured voice - perfect for bedtime stories"
    ballad: "Melodic, musical voice - ideal for fairy tales"
    coral: "Warm, friendly voice - excellent for character narration"
    echo: "Clear, articulate voice - good for educational stories"
    fable: "British accent, expressive voice - perfect for classic tales"
    nova: "Bright, engaging female voice - excellent for adventure stories"
    onyx: "Deep, rich male voice - great for wise characters"
    shimmer: "Gentle, soothing voice - ideal for emotional moments"
    sage: "Wise, contemplative voice - perfect for meaningful stories"
    # Note: Additional premium voices available with gpt-4o-mini-tts

# Emotional storytelling configuration for future v3 alpha upgrade
emotional_storytelling:
  # ElevenLabs v3 alpha audio tags for enhanced emotional expression
  enabled: false  # Enable when upgrading to v3 alpha model
  stability_preset: "creative"  # Options: creative, natural, robust
  audio_tags:
    excitement: "[excited]"
    whisper: "[whispers]" 
    dramatic: "[dramatically]"
    cheerful: "[cheerfully]"
    mysterious: "[mysteriously]"
    scared: "[nervously]"
    happy: "[joyfully]"
    pause: "[pause]"
    # Character voices for different story elements
    monster_voice: "[deep voice]"
    child_voice: "[soft-spoken]"
    narrator_awe: "[awe]"
    dramatic_moment: "[dramatic tone]"