

/// Story model representing a story generated by Mira
class Story {
  final String id;
  final String title;
  final String content;
  final String? imageUrl;
  final String? audioUrl;
  final DateTime createdAt;
  final String childName;
  final StoryStatus status;

  Story({
    required this.id,
    required this.title,
    required this.content,
    this.imageUrl,
    this.audioUrl,
    required this.createdAt,
    required this.childName,
    this.status = StoryStatus.pending,
  });

  Story copyWith({
    String? id,
    String? title,
    String? content,
    String? imageUrl,
    String? audioUrl,
    DateTime? createdAt,
    String? childName,
    StoryStatus? status,
  }) {
    return Story(
      id: id ?? this.id,
      title: title ?? this.title,
      content: content ?? this.content,
      imageUrl: imageUrl ?? this.imageUrl,
      audioUrl: audioUrl ?? this.audioUrl,
      createdAt: createdAt ?? this.createdAt,
      childName: childName ?? this.childName,
      status: status ?? this.status,
    );
  }
}

/// Status of a story in the approval workflow
enum StoryStatus {
  pending,
  approved,
  rejected,
}

/// Format DateTime to a human-readable string
extension DateTimeFormatting on DateTime {
  String toReadableString() {
    final now = DateTime.now();
    final difference = now.difference(this);
    
    if (difference.inDays == 0) {
      return 'Today, ${hour.toString().padLeft(2, '0')}:${minute.toString().padLeft(2, '0')}';
    } else if (difference.inDays == 1) {
      return 'Yesterday, ${hour.toString().padLeft(2, '0')}:${minute.toString().padLeft(2, '0')}';
    } else if (difference.inDays < 7) {
      const weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
      return '${weekdays[weekday - 1]}, ${hour.toString().padLeft(2, '0')}:${minute.toString().padLeft(2, '0')}';
    } else {
      return '${day.toString().padLeft(2, '0')}-${month.toString().padLeft(2, '0')}-$year';
    }
  }
}
