# Mira Storyteller AI Agents Configuration
agents:
  vision:
    vendor: "google"  # Options: google, openai, anthropic
    model: "gemini-2.0-flash-exp"
    api_key: ${GOOGLE_API_KEY}
    fallback:
      vendor: "openai"
      model: "gpt-4-vision-preview"
      api_key: ${OPENAI_API_KEY}
    prompts:
      image_caption:
        default: |
          Describe this image focusing on 3-5 main visual elements:
          - Main subject/character (identify specific objects when recognizable)
          - Colors and textures
          - Setting/background
          - Notable objects
          - Overall mood
          Be factual but include specific names for recognizable items.
      
  storyteller:
    # Current: mistral-medium (5.5s, reliable JSON, good quality)
    # Alternatives: gpt-3.5-turbo (faster), gpt-4o-mini (better quality)
    vendor: "mistral"  # Options: mistral, openai, google
    model: "mistral-medium-latest"
    api_key: ${MISTRAL_API_KEY}
    max_tokens: 800
    temperature: 0.7
    word_count: "500"  # Target story length in words
    prompts:
      story_generation:
        system: |
          You are a creative children's storyteller. Create engaging, family-friendly stories.
          The stories should be imaginative, positive, and appropriate for children aged 3-8 years old.
        user: |
          Create a children's story and return it as valid JSON.

          Story details:
          - Base story on: {image_description}
          - Child's name: {kid_name}
          - Age group: {age_group}
          - Language: {language}
          - Target length: {word_count} words
          - Additional context: {additional_context}

          Requirements:
          - Story should be imaginative, positive, and age-appropriate
          - Include the child's name naturally in the story
          - Format the story with 4-5 paragraphs separated by double newlines (\n\n)
          - Each paragraph should be 2-4 sentences
          - Do not include any text except JSON in your response
          - Do not return Markdown or HTML

          Return ONLY this JSON structure:
          {{
            "title": "An engaging story title",
            "content": "The complete story content..."
          }}
    
  voice:
    # TTS configuration per language
    languages:
      en:
        vendor: "elevenlabs"
        api_key: ${ELEVENLABS_API_KEY}
        voice: "callum"
        voice_id: "N2lVS1w4EtoT3dr4eOWO"
        model: "eleven_multilingual_v2"
        settings:
          stability: 0.5
          similarity_boost: 0.5
          style: 0.0
          use_speaker_boost: true
          speed: 0.8
      ru:
        vendor: "elevenlabs"
        api_key: ${ELEVENLABS_API_KEY}
        voice: "nina"
        voice_id: "N8lIVPsFkvOoqev5Csxo"
        model: "eleven_multilingual_v2"
        settings:
          stability: 0.4
          similarity_boost: 0.6
          style: 0.4
          use_speaker_boost: true
          speed: 0.9
      lv:
        vendor: "openai"
        api_key: ${OPENAI_API_KEY}
        voice: "sage"
        model: "tts-1-hd"
        settings:
          speed: 0.95
          response_format: "flac"
    
    # Voice alternatives for reference
    available_voices:
      elevenlabs:
        callum: "N2lVS1w4EtoT3dr4eOWO"  # Warm male voice (EN)
        nina: "N8lIVPsFkvOoqev5Csxo"    # Professional female voice (RU)
        rachel: "21m00Tcm4TlvDq8ikWAM"  # Gentle female voice (EN)
      openai:
        sage: "Calm, thoughtful voice"    # Current LV choice
        coral: "Expressive female voice"
        nova: "Bright, engaging voice"
      
  speech:
    vendor: "openai"
    vendors:
      openai:
        model: "whisper-1"
        api_key: ${OPENAI_API_KEY}
        settings:
          response_format: "text"
          temperature: 0.0
    
  appearance:  # Appearance extraction from photos
    vendor: "google"  # Google Vision API works well for photos
    model: "gemini-2.0-flash-exp"
    api_key: ${GOOGLE_API_KEY}
    max_tokens: 200
    temperature: 0.3  # Lower temperature for consistent descriptions
    prompts:
      appearance_extraction: |
        Analyze this photo of {kid_name} (age {age}) and create a natural, warm description of their appearance suitable for children's story personalization.

        Focus on:
        - Hair (color, style, length, texture)
        - Eyes (color, shape)
        - Distinctive features (glasses, freckles, dimples)
        - Clothing style preferences if visible
        - Overall expression/personality that shows through

        Write in a warm, positive tone as if describing the child to a storyteller. Keep it concise (2-3 sentences, under 100 words).

        Example format: "Curly brown hair that bounces when she runs, bright green eyes that sparkle with curiosity, and a gap-toothed smile that lights up her whole face."

        Description:

  artist:  # Future - Image Generation
    vendor: "openai"
    model: "dall-e-3"
    api_key: ${OPENAI_API_KEY}